# Generated by Django 5.0.1 on 2024-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_of_uses',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во использований'),
        ),
    ]
